name: smooth_normalizing_flows
channels:
        - pytorch
        - conda-forge
dependencies:

        # hardware restriction
        - cudatoolkit=10.1
        
          # python
        - python
        - matplotlib
        - jupyter
        - notebook
        - jupyterlab

        # testing
        - pytest
        - pytest-cov
        - pytest-runner
        
        # simulation
        - openmm>=7.5.1
        - nglview
        - mdtraj
        
        # data science
        - scipy
        - pandas
        
        # machine learning
        - pytorch>=1.8
        - torchvision>=0.8
        - pytorch-lightning
        - scikit-learn
        - tensorboard
        
